# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        app:
            id: app.user_provider

    encoders:
        "%app.current_user.class%": sha256

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        # login_firewall:
        #     pattern:   ^/login$
        #     anonymous: ~
        main:
            anonymous: true
            form_login:
                login_path: login
                check_path: login_check
            remember_me:
                secret:   '%secret%'
                lifetime:  8640000
            logout:
                path: logout

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    access_control:
        - { path: ^/admin, role: ROLE_ADMIN }
